#pragma once

#include <opencv2/opencv.hpp>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

#include "ellipse_processing.hpp"
#include "orientation_processing.hpp"
#include "perspective_processing.hpp"
#include "wire_model.hpp"
#include "geometry_calibration.hpp"

/**
 * #1510: ONE PHYSICAL BOARD, THREE VIEWS, SHARED MILLIMETRE COORDINATES.
 *
 * Everything upstream of this header fits IMAGE shapes: six ring ellipses fitted or
 * traced per camera, held to each other by #1485's bands, and a twenty-fold wire ring
 * generated from #1467's plane. What none of it states is the thing #1488 needs before
 * any two cameras can be reconciled in board space: that all three cameras are looking
 * at ONE board whose dimensions are known in millimetres, and that each camera's view is
 * that one board under one projective map.
 *
 * This module states it. A `BoardProfile` is the physical board -- scoring radii, twenty
 * sectors at eighteen degrees, the number sequence, an orientation convention, and the
 * board's appearance facts (rim, surround) kept SEPARATE from its scoring facts, because
 * Winmau's "450 mm" is the Blade 6's overall diameter and nothing a dart is ever scored
 * against. A `BoardFit` is one camera's mapping of that profile into its image, with the
 * residual of every observed landmark against the model's prediction, in pixels and in
 * millimetres, and a verdict that REJECTS by name what the issue says must be rejected:
 * a rotation nothing anchored, a ring that is not where the board puts it, support too
 * thin to constrain the fit, and a residual pattern no flat board explains.
 *
 * WHAT THE FIT IS MADE OF, AND WHAT IS THEREFORE HELD OUT. The map is #1467's
 * construction, not a new solver: H carries the unit circle to the ray-traced doubles
 * ellipse and the origin to the detected bull, which pins the projective map up to the
 * O(2) that wire_model.hpp derives, and the millimetre scale is #1499's de-biased board
 * reach -- both doubles marks, bloom cancelling. So the fit CONSUMES the doubles pair
 * and the bull, and everything else on the calibration is untouched by it: the treble
 * pair, the 25 ring, the bullseye and the twenty wire boundaries are OBSERVATIONS the
 * model must predict, which is the held-out validation the issue demands. A fit that
 * predicts landmarks it never read is evidence; one validated only against its own
 * endpoints is not, and the acceptance below refuses a camera on which nothing
 * independent was observed at all.
 *
 * WHY IMAGE ELLIPSES ARE NEVER SCALED. Perspective preserves neither concentric image
 * centres nor image-radius ratios: the bull's image sits OFF the doubles ellipse's
 * centre on every tilted camera (that offset is the whole tilt signal, wire_model.hpp),
 * and a 99 mm circle's image is not 99/170 of the 170 mm circle's. Every model boundary
 * here is therefore generated by mapping the millimetre circle through H, and every
 * comparison is made along a ray from the bull -- the same geometry scorePoint judges
 * membership in.
 *
 * LENS DISTORTION IS A QUANTIFIED LIMITATION, NOT A SILENT ABSORPTION. The map is
 * projective, so radial lens distortion is exactly what it cannot represent; nothing
 * here estimates a distortion model because one empty-board calibration frame per camera
 * does not constrain one (#1513 is that investigation). What this module does instead is
 * measure the limitation where it would bite: the signed millimetre residual of each
 * held-out ring is the bound on everything the flat model failed to explain -- lens
 * distortion, mask bloom (#1499 measured the traced edge sitting past the paint), and
 * board tolerance together -- and a residual outside the ring's own #1485 band refuses
 * the fit rather than absorbing it. The bands are the documented tolerance: derived from
 * the board's millimetres as geometric means between adjacent rings, never fitted to
 * footage.
 *
 * WHAT PHASE 1 DOES NOT DO. Nothing consumes this fit yet: scoring still walks the
 * per-ring ellipses, and nothing here is persisted -- DartboardCalibration's bytes are
 * untouched, so the calibration cache (#1330) neither grows nor invalidates. Generating
 * the scoring boundaries FROM the model, and persisting profile/version/transform with
 * the cache-compatibility the issue requires, is the second half of #1510 and it builds
 * on the `imageOfBoard`/`boardPointOf` pair below.
 */
namespace board_model
{
    /**
     * The physical board, in millimetres, versioned.
     *
     * The scoring radii are `perspective_processing::DartboardSpec`'s numbers -- the
     * board facts every stage already divides by (WDF spec; a Blade 6 is built to it,
     * #1499 measured both our rigs' paint on it and the Unicorn control's too). They are
     * COPIED from the spec by profileFromSpec rather than restated, so a corrected spec
     * corrects every profile made from it.
     *
     * `rimRadiusMm` is an APPEARANCE fact and scoring never touches it: Winmau lists the
     * Blade 6's overall diameter as 450 mm (manufacturer's page, on #1510), so the rim
     * sits at 225 mm -- 55 mm of number ring and surround outside the last wire a dart
     * can score on. It exists so that a later consumer (the ROI, the number reader) has
     * the board's edge without anyone mistaking it for the scoring edge again.
     *
     * A club board that is not a Blade 6 is ANOTHER PROFILE, not another code path
     * (#1501): same spec radii if it is a WDF board, its own name, version and rim.
     */
    struct BoardProfile
    {
        const char *name = "winmau-blade-6";
        int version = 1;

        // Scoring facts, millimetres from board centre (board facts, DartboardSpec's).
        float bullRadiusMm = 6.35f;
        float bull25RadiusMm = 15.9f;
        float innerTripleRadiusMm = 99.0f;
        float outerTripleRadiusMm = 107.0f;
        float innerDoubleRadiusMm = 162.0f;
        float outerDoubleRadiusMm = 170.0f;

        // Appearance facts. Never scoring: 450 mm is the OVERALL diameter (Blade 6 fact).
        float rimRadiusMm = 225.0f;

        // Twenty sectors of eighteen degrees, the sequence clockwise from the 20 --
        // the same sequence orientation_processing::seqIndexOfWedge holds and
        // score_processing scores against. Stated here because the profile is the one
        // place the PHYSICAL board is described whole.
        int sectors = wire_model::kFold;

        /**
         * Orientation convention, so three cameras mean one thing by "angle": board
         * angles are radians about the board centre; sector boundaries sit at a fitted
         * offset plus k times eighteen degrees; WHICH boundary starts the 20 is the
         * anchor's statement (observed star pattern, read numbers, or the operator's
         * OD_CAMERA_WEDGES), never an assumption -- a common physical model does not
         * resolve the twenty-fold ambiguity and this struct does not pretend to.
         * Handedness (the mirror wire_model.hpp names) is resolved downstream by ring
         * nesting, as before.
         */
        int wedgeAtIndex(int sequenceIndex) const
        {
            static const int sequence[20] = {20, 1, 18, 4, 13, 6, 10, 15, 2, 17, 3, 19, 7, 16, 8, 11, 14, 9, 12, 5};
            return (sequenceIndex >= 0 && sequenceIndex < 20) ? sequence[sequenceIndex] : -1;
        }

        /** The scoring radius, mm, of one of ellipse_processing's ring indices. */
        double ringRadiusMm(int ring) const
        {
            switch (ring)
            {
            case ellipse_processing::kInnerBull:
                return bullRadiusMm;
            case ellipse_processing::kOuterBull:
                return bull25RadiusMm;
            case ellipse_processing::kInnerTriple:
                return innerTripleRadiusMm;
            case ellipse_processing::kOuterTriple:
                return outerTripleRadiusMm;
            case ellipse_processing::kInnerDouble:
                return innerDoubleRadiusMm;
            default:
                return outerDoubleRadiusMm;
            }
        }
    };

    /** The default profile, from the spec the whole pipeline already divides by. */
    inline BoardProfile profileFromSpec(const perspective_processing::DartboardSpec &spec,
                                        const char *name = "winmau-blade-6", int version = 1,
                                        float rimRadiusMm = 225.0f)
    {
        BoardProfile profile;
        profile.name = name;
        profile.version = version;
        profile.bullRadiusMm = spec.bullRadius;
        profile.bull25RadiusMm = spec.bull25Radius;
        profile.innerTripleRadiusMm = spec.innerTripleRadius;
        profile.outerTripleRadiusMm = spec.outerTripleRadius;
        profile.innerDoubleRadiusMm = spec.innerDoubleRadius;
        profile.outerDoubleRadiusMm = spec.outerDoubleRadius;
        profile.rimRadiusMm = rimRadiusMm;
        return profile;
    }

    /**
     * How many rays must have supported the doubles reference before the map built on it
     * is believed: the same 50 of 120 rays (at 3 degrees) the ray trace itself demands
     * before it fits an ellipse at all (EllipseParams::minValidRays). Restated rather
     * than reached for because EllipseParams is a parameter struct a caller may have
     * altered, and the fit's own floor must not move with a caller's experiment.
     */
    inline constexpr int kMinSupportRays = 50;

    /** How many board angles each ring is compared on: the ray trace's own 120 at 3°. */
    inline constexpr int kResidualRays = 120;

    /** One observed landmark ring, against the model's prediction of it. */
    struct RingResidual
    {
        bool observed = false;  // a non-zero ellipse was on the calibration for this ring
        bool heldOut = false;   // the fit never read it, so it independently tests the fit
        bool inBand = false;    // its median model-space radius is inside its #1485 band
        int rays = 0;           // rays on which both the model and the observation answered
        double medianObservedMm = 0.0; // where the model says the observed edge sits
        double modelMm = 0.0;          // where the profile says it should
        double signedMedianMm = 0.0;   // observed minus model: the distortion+bloom bound
        double rmsPx = 0.0;            // radial, along rays from the bull
        double maxPx = 0.0;
    };

    /**
     * One camera's fit of the one board. Owns strings and matrices freely: it is never
     * written to the calibration cache (#1330) and never outlives the process.
     */
    struct BoardFit
    {
        bool planeBuilt = false;
        bool geometryAccepted = false;  // every observed landmark is where the board puts it
        bool rotationResolved = false;  // an anchor names which boundary starts the 20
        bool accepted = false;          // both of the above
        std::string story;              // the whole verdict, in words a log reader can act on

        wire_model::Plane plane;   // board plane <-> image, unit circle = doubles ring
        double unitPerMm = 0.0;    // plane units per millimetre (de-biased, #1499)
        double pxPerMmAtCentre = 0.0; // geometric-mean pixel scale at the bull
        double deBias = 1.0;       // boardReach / outer traced reach, 1.0 where unavailable

        // The twenty-fold sector check over the calibration's own wire boundaries.
        double wireCoherence = 0.0;   // R of the endpoints at fold twenty
        double wireOffset = 0.0;      // radians, board space
        double wireRmsDeg = 0.0;      // endpoints against the fitted twenty-fold comb
        int wireBoundaries = 0;

        int supportRays = 0;          // rays that supported the doubles reference
        int heldOutObserved = 0;      // held-out rings a residual could be measured on
        int heldOutInBand = 0;

        RingResidual rings[ellipse_processing::kRingCount + 1]; // +1: the outer doubles reference
    };

    /** Where a board point (mm, board angle) lands in this camera's image. */
    inline cv::Point2f imageOfBoard(const BoardFit &fit, double radiusMm, double theta)
    {
        return wire_model::imageOfBoardAngle(fit.plane, theta, radiusMm * fit.unitPerMm);
    }

    /** Where an image point sits on the board: millimetres from centre, and its angle. */
    inline cv::Point2f boardPointOf(const BoardFit &fit, const cv::Point2f &image)
    {
        const cv::Vec3d q = fit.plane.Hinv * cv::Vec3d(image.x, image.y, 1.0);
        if (q[2] == 0.0 || !(fit.unitPerMm > 0.0))
        {
            return cv::Point2f(0.f, 0.f);
        }
        return cv::Point2f((float)(q[0] / q[2] / fit.unitPerMm), (float)(q[1] / q[2] / fit.unitPerMm));
    }

    /**
     * Distance from `origin` along unit `dir` to the far boundary of `e`, negative where
     * the ray never crosses it -- the same quadratic i1485's radius census and the
     * scorer's ruler use, restated here because this header must stand without the
     * detection half of the tree.
     */
    inline double rayReachToEllipse(cv::Point2f origin, cv::Point2f dir, const cv::RotatedRect &e)
    {
        const double a = e.size.width / 2.0, b = e.size.height / 2.0;
        if (!(a > 0.0) || !(b > 0.0))
        {
            return -1.0;
        }
        const double th = -e.angle * CV_PI / 180.0, c = std::cos(th), s = std::sin(th);
        const cv::Point2f rel = origin - e.center;
        const double x0 = rel.x * c - rel.y * s, y0 = rel.x * s + rel.y * c;
        const double dx = dir.x * c - dir.y * s, dy = dir.x * s + dir.y * c;
        const double A = dx * dx / (a * a) + dy * dy / (b * b);
        const double B = 2.0 * (x0 * dx / (a * a) + y0 * dy / (b * b));
        const double C = x0 * x0 / (a * a) + y0 * y0 / (b * b) - 1.0;
        const double disc = B * B - 4 * A * C;
        if (disc < 0 || !(A > 0))
        {
            return -1.0;
        }
        const double t = (-B + std::sqrt(disc)) / (2 * A);
        return t > 0 ? t : -1.0;
    }

    namespace detail
    {
        inline std::string fmt(const char *pattern, double v)
        {
            char buf[48];
            snprintf(buf, sizeof(buf), pattern, v);
            return buf;
        }

        /** Median of a small vector, by copy; 0.0 for an empty one. */
        inline double medianOf(std::vector<double> v)
        {
            if (v.empty())
            {
                return 0.0;
            }
            std::sort(v.begin(), v.end());
            return v[v.size() / 2];
        }

        /** Measure one observed ring ellipse against the model circle at `radiusMm`. */
        inline RingResidual measureRing(const BoardFit &fit, const cv::RotatedRect &observed,
                                        double radiusMm, bool heldOut, const cv::Point2f &bull)
        {
            RingResidual r;
            r.heldOut = heldOut;
            r.modelMm = radiusMm;
            if (!(ellipse_processing::ringReach(observed) > 0.0))
            {
                return r; // a zeroed ellipse is a ring #1485 refused or nothing fitted: absent
            }
            r.observed = true;

            std::vector<double> obsMm, pxErr;
            obsMm.reserve(kResidualRays);
            for (int i = 0; i < kResidualRays; i++)
            {
                const double theta = 2.0 * CV_PI * i / kResidualRays;
                const cv::Point2f model = imageOfBoard(fit, radiusMm, theta);
                cv::Point2f dir = model - bull;
                const double len = std::sqrt((double)dir.x * dir.x + (double)dir.y * dir.y);
                if (!(len > 0.0))
                {
                    continue;
                }
                dir *= (float)(1.0 / len);
                const double reach = rayReachToEllipse(bull, dir, observed);
                if (!(reach > 0.0))
                {
                    continue;
                }
                const cv::Point2f obs = bull + dir * (float)reach;
                const cv::Point2f board = boardPointOf(fit, obs);
                const double mm = std::sqrt((double)board.x * board.x + (double)board.y * board.y);
                if (!std::isfinite(mm))
                {
                    continue;
                }
                obsMm.push_back(mm);
                const double err = reach - len;
                pxErr.push_back(err);
                r.maxPx = std::max(r.maxPx, std::fabs(err));
            }
            r.rays = (int)obsMm.size();
            if (r.rays == 0)
            {
                r.observed = false;
                return r;
            }
            r.medianObservedMm = medianOf(obsMm);
            r.signedMedianMm = r.medianObservedMm - radiusMm;
            double sumsq = 0.0;
            for (double e : pxErr)
            {
                sumsq += e * e;
            }
            r.rmsPx = std::sqrt(sumsq / (double)pxErr.size());
            return r;
        }
    }

    /**
     * Fit the one board to one camera's calibration, and judge it.
     *
     * Pure over the calibration struct: no frame, no mask, no globals, so a tester holds
     * every verdict below with synthetic geometry and the real pipeline holds it with a
     * real one (#1338's shape). `conicOfDoubles` is #1423's identity of the traced conic,
     * from wire_processing::conicOfDoublesFor -- taken as a parameter for the same reason
     * wire_model::planeOf takes it: which ring a conic is, is decided in one place and
     * this is not it.
     */
    inline BoardFit fitBoardToCamera(const BoardProfile &profile, const DartboardCalibration &calib,
                                     double conicOfDoubles = 1.0)
    {
        using namespace ellipse_processing;
        BoardFit fit;
        const cv::Point2f bull((float)calib.bullCenter.x, (float)calib.bullCenter.y);

        if (!calib.ellipses.hasValidDoubles || !(ringReach(calib.ellipses.outerDoubleEllipse) > 0.0))
        {
            fit.story = "REJECTED: no ray-traced doubles ring, so there is no reference to fit "
                        "the board through";
            return fit;
        }

        fit.supportRays = calib.ellipses.validOuterPoints;
        fit.plane = wire_model::planeOf(calib.ellipses.outerDoubleEllipse, bull, conicOfDoubles);
        if (!fit.plane.built)
        {
            fit.story = "REJECTED: no board plane could be built -- the bull is not inside the "
                        "ring it is supposed to centre, or the conic has no radius";
            return fit;
        }
        fit.planeBuilt = true;

        // The millimetre scale. Unit 1.0 of the plane is the TRACED doubles ellipse
        // (times #1423's identity), and #1499 measured that trace sitting past the paint
        // by the mask's own bloom -- so the true 170 mm wire sits at deBias of it, where
        // deBias is the two-mark board over the outer mark. Only meaningful when the
        // conic really is the doubles ring; a treble-identified conic keeps deBias 1.0
        // and says so, because the doubles-marks average is a statement about a pair
        // this camera did not trace as a pair.
        const double outerReach = ringReach(calib.ellipses.outerDoubleEllipse);
        std::string scaleStory;
        if (conicOfDoubles == 1.0)
        {
            const double board = deBiasedBoardReach(calib.ellipses);
            fit.deBias = (board > 0.0) ? board / outerReach : 1.0;
            scaleStory = (fit.deBias != 1.0)
                             ? "scale de-biased by the two doubles marks (#1499), factor " +
                                   detail::fmt("%.4f", fit.deBias)
                             : "scale from the outer doubles mark alone (inner mark unusable)";
        }
        else
        {
            fit.deBias = 1.0;
            scaleStory = "scale through #1423's ring identity (the traced conic is not the "
                         "doubles ring), un-de-biased";
        }
        fit.unitPerMm = fit.deBias / (double)profile.outerDoubleRadiusMm;
        const double a = calib.ellipses.outerDoubleEllipse.size.width * 0.5 * conicOfDoubles;
        const double b = calib.ellipses.outerDoubleEllipse.size.height * 0.5 * conicOfDoubles;
        fit.pxPerMmAtCentre = std::sqrt(a * b) * fit.deBias / (double)profile.outerDoubleRadiusMm;

        std::vector<std::string> refusals;

        if (fit.supportRays < kMinSupportRays)
        {
            refusals.push_back("insufficient coverage: " + std::to_string(fit.supportRays) + " of " +
                               std::to_string(kResidualRays) + " rays support the doubles reference "
                               "where the trace itself demands " + std::to_string(kMinSupportRays));
        }

        // Every ring on the calibration, against the model's prediction of it. The
        // doubles pair and the bull built the map, so they are marked as the fit's own;
        // the treble pair and both bull rings are held out and are the validation.
        int ringOf[kRingCount + 1] = {kInnerBull, kOuterBull, kInnerTriple, kOuterTriple, kInnerDouble, kRingCount};
        for (int i = 0; i <= kRingCount; i++)
        {
            const int ring = ringOf[i];
            const bool heldOut = (ring != kInnerDouble && ring != kRingCount);
            const cv::RotatedRect &observed =
                (ring == kRingCount) ? calib.ellipses.outerDoubleEllipse
                                     : ringEllipse(const_cast<EllipseBoundaryData &>(calib.ellipses), ring);
            RingResidual r = detail::measureRing(fit, observed, profile.ringRadiusMm(ring), heldOut, bull);
            if (r.observed)
            {
                const double spans = r.medianObservedMm / (double)profile.outerDoubleRadiusMm;
                const double low = (ring == kRingCount) ? ringBandHigh(kInnerDouble) : ringBandLow(ring);
                const double high = (ring == kRingCount) ? 1.0 / ringBandHigh(kInnerDouble) : ringBandHigh(ring);
                r.inBand = spans >= low && spans <= high;
                if (heldOut)
                {
                    fit.heldOutObserved++;
                    if (r.inBand)
                    {
                        fit.heldOutInBand++;
                    }
                    else
                    {
                        refusals.push_back(std::string(ringName(ring)) + " sits at " +
                                           detail::fmt("%.1f", r.medianObservedMm) + " mm in model space where its band is " +
                                           detail::fmt("%.1f", low * profile.outerDoubleRadiusMm) + ".." +
                                           detail::fmt("%.1f", high * profile.outerDoubleRadiusMm) + " mm -- wrong ring "
                                           "identity, or a distortion no flat board explains");
                    }
                }
            }
            fit.rings[i] = r;
        }

        if (fit.heldOutObserved == 0)
        {
            refusals.push_back("nothing independent tests this fit: no ring the map was not built "
                               "from was observed, so partial visibility does not constrain it");
        }

        // The twenty sector boundaries this camera carries, against the model's comb.
        // Mostly they were GENERATED by wire_model since #1467, so a clean camera reads
        // near-zero here; what this catches is a calibration whose boundaries do not
        // form a twenty-fold ring at all -- a counted ring of intruders, or a synthetic
        // wrong-rotation plant -- which no anchor should be trusted to index into.
        {
            std::vector<cv::Point2f> endpoints(calib.wires.wireEndpoints.begin(),
                                               calib.wires.wireEndpoints.end());
            fit.wireBoundaries = (int)endpoints.size();
            if (fit.wireBoundaries == wire_model::kFold)
            {
                fit.wireCoherence = wire_model::coherenceAtFold(fit.plane, endpoints, wire_model::kFold);
                const wire_model::Fit comb = wire_model::fitTwentyFold(fit.plane, endpoints);
                fit.wireOffset = comb.offset;
                fit.wireRmsDeg = comb.rmsResidualDeg;
                if (fit.wireCoherence < wire_model::minimumCoherence())
                {
                    // #1510 Phase 2 watch item: camera 1 once read NOBOARD at R=0.578
                    // against this same 0.60 gate. A refusal 0.022 under a threshold and
                    // one 0.4 under it are different findings, so the MARGIN is printed
                    // beside the verdict rather than left for a reader to subtract.
                    refusals.push_back("the twenty boundaries this camera carries do not form a "
                                       "twenty-fold ring (R=" + detail::fmt("%.3f", fit.wireCoherence) +
                                       " against a minimum of " +
                                       detail::fmt("%.2f", wire_model::minimumCoherence()) +
                                       ", margin " +
                                       detail::fmt("%+.3f", fit.wireCoherence - wire_model::minimumCoherence()) +
                                       "), so no rotation can be indexed on them");
                }
            }
            else
            {
                refusals.push_back("only " + std::to_string(fit.wireBoundaries) + " of " +
                                   std::to_string(wire_model::kFold) + " sector boundaries are on this "
                                   "calibration, so the model's sectors have nothing to be held to");
            }
        }

        fit.geometryAccepted = refusals.empty();

        // The twenty-fold ambiguity is resolved by an anchor or not at all (#1363,
        // #1486, #1498): the scorer's own question, asked of the scorer's own field.
        std::string rotationStory;
        if (orientation_processing::wedgeCanBeRead(calib.orientation))
        {
            fit.rotationResolved = true;
            rotationStory = "rotation " + orientation_processing::howItReads(calib.orientation);
        }
        else
        {
            // The remedy is said here even where howItReads' own branch does not carry
            // it, because for THIS fit an unresolved rotation is always answerable the
            // same two ways: an observed anchor or the operator's statement.
            rotationStory = "the twenty-sector rotation is UNRESOLVED (" +
                            orientation_processing::howItReads(calib.orientation) +
                            "); observe an anchor or state one with OD_CAMERA_WEDGES";
        }

        fit.accepted = fit.geometryAccepted && fit.rotationResolved;

        // The verdict, whole: profile, scale, each ring's residual against the model's
        // prediction (held-out marked, because those are the evidence), the sector comb,
        // the rotation, and every refusal by name. #1321's rule on the sentence -- the
        // numbers, against each other, where a reader without --debug sees them.
        std::string rows;
        for (int i = 0; i <= kRingCount; i++)
        {
            const RingResidual &r = fit.rings[i];
            if (!r.observed)
            {
                continue;
            }
            const int ring = ringOf[i];
            rows += rows.empty() ? "" : ", ";
            rows += std::string(ring == kRingCount ? "the doubles ring" : ringName(ring)) +
                    (r.heldOut ? " [held-out] " : " [fitted] ") +
                    detail::fmt("%+.1f", r.signedMedianMm) + " mm (rms " + detail::fmt("%.1f", r.rmsPx) +
                    " px over " + std::to_string(r.rays) + " rays)";
        }
        fit.story = std::string("board model [") + profile.name + " v" + std::to_string(profile.version) +
                    "]: " + scaleStory + ", " + detail::fmt("%.2f", fit.pxPerMmAtCentre) +
                    " px/mm at the bull, tilt " + detail::fmt("%.3f", fit.plane.tilt) + "; residuals " +
                    (rows.empty() ? "none measurable" : rows) +
                    " -- signed medians bound what the flat projective model does not explain "
                    "(lens distortion is not modelled, #1513); sectors R=" +
                    detail::fmt("%.3f", fit.wireCoherence) + " (margin " +
                    detail::fmt("%+.3f", fit.wireCoherence - wire_model::minimumCoherence()) +
                    " over the " + detail::fmt("%.2f", wire_model::minimumCoherence()) +
                    " gate) rms " + detail::fmt("%.1f", fit.wireRmsDeg) +
                    " deg over " + std::to_string(fit.wireBoundaries) + " boundaries; " + rotationStory + "; " +
                    (fit.accepted ? "ACCEPTED: " + std::to_string(fit.heldOutInBand) + " of " +
                                        std::to_string(fit.heldOutObserved) +
                                        " held-out rings are where this board's millimetres put them"
                                  : "REJECTED: ");
        if (!fit.accepted)
        {
            std::string why;
            for (const std::string &r : refusals)
            {
                why += (why.empty() ? "" : "; ") + r;
            }
            if (!fit.rotationResolved)
            {
                why += (why.empty() ? "" : "; ") + rotationStory;
            }
            fit.story += why;
        }
        return fit;
    }

    // ---- #1510 Phase 2: the fitted model ANSWERS SCORING QUESTIONS ---------------------
    //
    // Nothing below replaces the published score path. scorePoint still walks the
    // per-ring ellipses; these functions are the model's own answer to the same
    // question, pure over the fit (#1338's shape), measured beside the existing answer
    // under OD_MODEL_SCORE=on before anything is wired (the paint-containment census,
    // testers/i1510p2_inside.sh).

    /**
     * Which boundary starts the 20, stated on the BOARD rather than as a wire index.
     *
     * The existing path's anchor is `wedge20WireIndex`, an index into a store of image
     * points sorted by image angle about the bull, walked in that order by
     * findWedgeSlot. The model scores in board angles, so the anchor must say two
     * things in board space: WHERE the 20's first boundary sits (`theta20`, snapped to
     * the fitted comb so every sector boundary is the comb's rather than one
     * endpoint's), and WHICH WAY the number sequence advances (`advance`) -- the
     * homography fixes handedness per camera and nothing here may assume it, which is
     * the mirror wire_model.hpp names. Both are read off the same endpoint store the
     * existing path indexes, so the two scorers cannot disagree about what the anchor
     * meant.
     */
    struct ModelAnchor
    {
        bool resolved = false;
        double theta20 = 0.0; // board angle, radians, of the boundary the 20 starts at
        double advance = 1.0; // +1: the sequence advances with increasing board angle; -1 mirrored
    };

    namespace detail
    {
        /** Wrap to (-pi, pi]. */
        inline double wrapToPi(double a)
        {
            while (a > CV_PI)
            {
                a -= 2.0 * CV_PI;
            }
            while (a <= -CV_PI)
            {
                a += 2.0 * CV_PI;
            }
            return a;
        }

        /** Wrap to [0, 2*pi). */
        inline double wrapTo2Pi(double a)
        {
            a = std::fmod(a, 2.0 * CV_PI);
            return a < 0.0 ? a + 2.0 * CV_PI : a;
        }
    }

    /**
     * The anchor, read off the calibration's own endpoint ring.
     *
     * `endpointsByImageAngle` is `calib.wires.wireEndpoints` as findWedgeSlot walks it;
     * `wedge20WireIndex` is the index the existing path would start at -- the camera's
     * own anchor or a derived one (#1486), decided by the CALLER exactly where
     * scorePoint decides it, so this function has no opinion about which anchor wins.
     * Unresolved (a short ring, a negative index, no plane) is `resolved == false`,
     * never a defaulted 20: asserting is the published path's behaviour, not the
     * model's.
     */
    inline ModelAnchor anchorOnBoard(const BoardFit &fit,
                                     const std::vector<cv::Point2f> &endpointsByImageAngle,
                                     int wedge20WireIndex)
    {
        ModelAnchor anchor;
        const int n = (int)endpointsByImageAngle.size();
        if (!fit.planeBuilt || n != wire_model::kFold || wedge20WireIndex < 0 || wedge20WireIndex >= n)
        {
            return anchor;
        }
        std::vector<double> theta(n);
        for (int k = 0; k < n; k++)
        {
            theta[k] = wire_model::boardAngleOf(fit.plane, endpointsByImageAngle[k]);
        }
        // The direction the store advances in board space. Each consecutive step is
        // one sector (about +-18 degrees); their sum over the ring is +-2*pi, so its
        // sign is the handedness and small per-step noise cannot flip it.
        double sum = 0.0;
        for (int k = 0; k < n; k++)
        {
            sum += detail::wrapToPi(theta[(k + 1) % n] - theta[k]);
        }
        anchor.advance = sum >= 0.0 ? 1.0 : -1.0;
        anchor.theta20 = fit.wireOffset +
                         std::round((theta[wedge20WireIndex] - fit.wireOffset) / wire_model::kSector) *
                             wire_model::kSector;
        anchor.resolved = true;
        return anchor;
    }

    /**
     * What the fitted board says one image point scores -- and HOW CLOSE the call was.
     *
     * The boundary distances are the point of the shape, not an extra: #1512's
     * uncertainty ladder needs to know that a D20 was 0.4 mm from the S20 wire, not
     * just that it was a D20, so a caller sees the tip's board-plane point in
     * millimetres and its distance to the nearest boundary of each kind.
     * `boundaryMm` is the one that could change THIS call: on a bull, an outer bull
     * or a miss the wedge decides nothing, so only the ring boundary counts there.
     */
    struct ModelScore
    {
        bool valid = false;      // the plane stood and the millimetre scale was positive
        cv::Point2f boardMm;     // the tip's board-plane point, millimetres from centre
        double radiusMm = 0.0;   // |boardMm|
        double thetaBoard = 0.0; // radians, board space

        std::string ringWord;   // bull, outer, single, triple, double; empty for a miss
        bool wedgeResolved = false;
        int sequenceIndex = -1; // 0..19 clockwise from the 20; -1 unresolved
        int segment = -1;       // 1..20; -1 on a bull ring, a miss, or unresolved
        std::string score = "MISS"; // the published vocabulary: S1..D20, BULL, OUTER, MISS.
                                    // "S?", "T?", "D?" where the ring is known and no
                                    // anchor resolves the wedge -- the model never
                                    // asserts the 20 the way #1346's fallback does.

        // #1512's seed. All in millimetres ON THE BOARD, signed distances made absolute.
        double ringBoundaryMm = -1.0;  // to the nearest of the six scoring radii
        double wedgeBoundaryMm = -1.0; // arc to the nearest sector boundary; -1 unresolved
        double boundaryMm = -1.0;      // the nearest boundary that could change this call
    };

    inline ModelScore scoreFromModel(const BoardProfile &profile, const BoardFit &fit,
                                     const ModelAnchor &anchor, const cv::Point2f &image)
    {
        ModelScore out;
        if (!fit.planeBuilt || !(fit.unitPerMm > 0.0))
        {
            return out;
        }
        out.valid = true;
        out.boardMm = boardPointOf(fit, image);
        out.radiusMm = std::sqrt((double)out.boardMm.x * out.boardMm.x +
                                 (double)out.boardMm.y * out.boardMm.y);
        out.thetaBoard = std::atan2((double)out.boardMm.y, (double)out.boardMm.x);

        const double radii[6] = {profile.bullRadiusMm, profile.bull25RadiusMm,
                                 profile.innerTripleRadiusMm, profile.outerTripleRadiusMm,
                                 profile.innerDoubleRadiusMm, profile.outerDoubleRadiusMm};
        out.ringBoundaryMm = std::fabs(out.radiusMm - radii[0]);
        for (int i = 1; i < 6; i++)
        {
            out.ringBoundaryMm = std::min(out.ringBoundaryMm, std::fabs(out.radiusMm - radii[i]));
        }

        std::string prefix;
        if (out.radiusMm <= profile.bullRadiusMm)
        {
            out.ringWord = "bull";
            out.score = "BULL";
        }
        else if (out.radiusMm <= profile.bull25RadiusMm)
        {
            out.ringWord = "outer";
            out.score = "OUTER";
        }
        else if (out.radiusMm <= profile.outerDoubleRadiusMm)
        {
            const bool triple = out.radiusMm > profile.innerTripleRadiusMm &&
                                out.radiusMm <= profile.outerTripleRadiusMm;
            const bool dbl = out.radiusMm > profile.innerDoubleRadiusMm;
            out.ringWord = triple ? "triple" : (dbl ? "double" : "single");
            prefix = triple ? "T" : (dbl ? "D" : "S");
        }
        // else: past the scoring edge -- a MISS, with radiusMm saying how far past.

        if (anchor.resolved)
        {
            const double delta = detail::wrapTo2Pi(anchor.advance * (out.thetaBoard - anchor.theta20));
            int slot = (int)(delta / wire_model::kSector);
            if (slot >= wire_model::kFold)
            {
                slot = wire_model::kFold - 1; // delta a rounding hair under 2*pi
            }
            out.wedgeResolved = true;
            out.sequenceIndex = slot;
            const double into = delta - slot * wire_model::kSector;
            out.wedgeBoundaryMm = out.radiusMm * std::min(into, wire_model::kSector - into);
            if (!prefix.empty())
            {
                out.segment = profile.wedgeAtIndex(slot);
                out.score = prefix + std::to_string(out.segment);
            }
        }
        else if (!prefix.empty())
        {
            out.score = prefix + "?";
        }

        // The boundary that could change the CALL. A bull, an outer bull and a miss are
        // ring decisions alone; a numbered ring can flip across either kind of wire.
        out.boundaryMm = (!prefix.empty() && out.wedgeResolved)
                             ? std::min(out.ringBoundaryMm, out.wedgeBoundaryMm)
                             : out.ringBoundaryMm;
        return out;
    }

    /**
     * The model, drawn whole on this camera's frame: every scoring circle the profile
     * states, generated through the fit (never a scaled image ellipse), the twenty
     * sector boundaries at the fitted comb, the observed ellipses thin beneath them so a
     * reader sees the residual as a gap, and the wire the anchor calls the 20's. Held-out
     * predictions are green, the fitted reference magenta, observations yellow.
     */
    inline void drawModelOverlay(cv::Mat &canvas, const BoardProfile &profile,
                                 const DartboardCalibration &calib, const BoardFit &fit)
    {
        using namespace ellipse_processing;
        if (!fit.planeBuilt || canvas.empty())
        {
            return;
        }
        const cv::Point2f bull((float)calib.bullCenter.x, (float)calib.bullCenter.y);

        // Observations first, thin, so the model is drawn over them.
        int ringOf[kRingCount + 1] = {kInnerBull, kOuterBull, kInnerTriple, kOuterTriple, kInnerDouble, kRingCount};
        for (int i = 0; i <= kRingCount; i++)
        {
            const cv::RotatedRect &observed =
                (ringOf[i] == kRingCount) ? calib.ellipses.outerDoubleEllipse
                                          : ringEllipse(const_cast<EllipseBoundaryData &>(calib.ellipses), ringOf[i]);
            if (ringReach(observed) > 0.0)
            {
                cv::ellipse(canvas, observed, cv::Scalar(0, 255, 255), 1);
            }
        }

        for (int i = 0; i <= kRingCount; i++)
        {
            const int ring = ringOf[i];
            const bool heldOut = (ring != kInnerDouble && ring != kRingCount);
            const cv::Scalar colour = heldOut ? cv::Scalar(0, 200, 0) : cv::Scalar(255, 0, 255);
            std::vector<cv::Point> circle;
            circle.reserve(kResidualRays);
            for (int k = 0; k < kResidualRays; k++)
            {
                const double theta = 2.0 * CV_PI * k / kResidualRays;
                const cv::Point2f p = imageOfBoard(fit, profile.ringRadiusMm(ring), theta);
                circle.push_back(cv::Point((int)std::lround(p.x), (int)std::lround(p.y)));
            }
            cv::polylines(canvas, circle, true, colour, 2);
        }

        // The sector comb, from the 25 ring to the doubles wire, at the fitted offset.
        for (int k = 0; k < wire_model::kFold; k++)
        {
            const double theta = fit.wireOffset + k * wire_model::kSector;
            const cv::Point2f inner = imageOfBoard(fit, profile.bull25RadiusMm, theta);
            const cv::Point2f outer = imageOfBoard(fit, profile.outerDoubleRadiusMm, theta);
            cv::line(canvas, inner, outer, cv::Scalar(255, 128, 0), 1);
        }

        // The wire the anchor calls the start of the 20, when one is resolved.
        if (fit.rotationResolved && calib.orientation.wedge20WireIndex >= 0 &&
            calib.orientation.wedge20WireIndex < (int)calib.wires.wireEndpoints.size())
        {
            const cv::Point2f w = calib.wires.wireEndpoints[calib.orientation.wedge20WireIndex];
            cv::line(canvas, bull, w, cv::Scalar(0, 0, 255), 2);
            cv::putText(canvas, "20-wire", w + cv::Point2f(4, -4), cv::FONT_HERSHEY_SIMPLEX, 0.5,
                        cv::Scalar(0, 0, 255), 1);
        }
        cv::putText(canvas, std::string(profile.name) + " v" + std::to_string(profile.version) +
                                (fit.accepted ? " ACCEPTED" : " REJECTED"),
                    cv::Point(10, 22), cv::FONT_HERSHEY_SIMPLEX, 0.6,
                    fit.accepted ? cv::Scalar(0, 200, 0) : cv::Scalar(0, 0, 255), 2);
    }
}
